### ISSUE TITLE
Index and values

### ISSUE THREAD

**Issue by Lucagtii** [chymtt/ReactNativeDropdownAndroid#13]
How I can set my custom unique index for each values, e.g.:
2 itme1
5 item2
6 item3
9 item4

Thanks,
Luca.

**Comment by chymtt** [comment]
I don't quite understand your need, but I think you can try using a dictionary to manage the index for each value, since the component doesn't support unique index

**Comment by Lucagtii** [comment]
Yes i mean exactly that. Usually select and dropdown allow to specify index and value. Ok, so I've used as workaround a search by item(string) on server side.
Thank you @chymtt !
