### ISSUE TITLE
In react-native 0.19 the values are not shown

### ISSUE THREAD

**Issue by danimasa** [chymtt/ReactNativeDropdownAndroid#17]
I upgraded my react-native version to 0.19, but after that the values on the Dropdown does't show. The dropdown appears but with no contents.

**Comment by JeJan** [comment]
same here with 0.20

**Comment by chymtt** [comment]
This is due to the breaking change in react-native 0.19.0. I have updated the component to adapt the change
@danimasa @JeJan 
Please update and see if the issue has been fixed

**Comment by danimasa** [comment]
Now all works well, Thanks.
