### ISSUE TITLE
Adding Styles

### ISSUE THREAD

**Issue by Sh3rawi** [chymtt/ReactNativeDropdownAndroid#2]
Are there any plans to expose styling the dropdown menu (backgroundColor, fontSize,...) ?

**Comment by chymtt** [comment]
Sorry, currently I'm occupied with other work so I have no plan for that yet. But a PR is always welcome!

**Comment by jforaker** [comment]
I was able to add `backgroundColor` but `color` threw an error in the console.

@chymtt could you point me in the direction on how to implement a simple change in color for the text?

**Comment by chymtt** [comment]
@jforaker : To change the text's style, you should look to alter the item's layout, which is on line 54 of Dropdown.java

```
spinnerArrayAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
```

I think you should start with making a custom layout for the dropdown item and then change the style from there.
P/S: Btw, I think the appropriate attribute to change text's color in this case is `textColor`. Hope it helps
