### ISSUE TITLE
Selected option

### ISSUE THREAD

**Issue by elmeister** [chymtt/ReactNativeDropdownAndroid#5]
When I am trying the sample code:

```
<Dropdown
        style={{ height: 20, width: 200}}
        values={[ '--Choose--', 'one', 2, 3.5, { four: 4 }, [ 5, 6, 7 ], false ]} 
        selected={1} onChange={(data) => { console.log(data); }} />
```

selected value in list is always 1st item, whatever passed as selected property.
Could you please advice the correct way to set selected element in `Dropdown` list?

**Comment by chymtt** [comment]
There seems to be a bug after upgrading to ReactNative 0.15.0. I've fixed it and it should be working as expected now. Please try reinstalling the component

**Comment by elmeister** [comment]
Work like a charm, thanks a lot!
