### ISSUE TITLE
How to set the default value before any selection?

### ISSUE THREAD

**Issue by zj-lin-zj** [chymtt/ReactNativeDropdownAndroid#6]
It seems like the selected props is the one to use however my app crashes when I use it in the code.
Thanks!

**Comment by chymtt** [comment]
It's true that the selected prop should be used. Could you please provide a
log or your code snippet? I can't work it out just based on what you said.

**Comment by zj-lin-zj** [comment]
I was playing with it for a while. My code snippet is as below

  < Dropdown
            style={styles.materialDropdown}
            values={this.props.data.material_list}
            selected={1} onChange={
              (data) => {
                this.setState({material:data.value});
              }} />

this.props.data.material_list is data passed from its owner view. The owner retrieves the material_list from server and updates it at componentDidMount(). I think the error is because the network call is asynchronous so the component could be accessing undefined. I tried to change to code to below where I add a default value for this.state.material_list and setState when the network call finishes but the selected props does not work anymore. Any idea how I can implement this feature?

  < Dropdown
            style={styles.materialDropdown}
            values={this.state.material_list}
            selected={1} onChange={
              (data) => {
                this.setState({material:data.value});
              }} />

**Comment by chymtt** [comment]
Thank you for pointing it out. It's a bug in my native code that make it refuse to update the "selected" value after re-rendering. I've fixed the issue and pushed it, please try it out to see if your problem persists.
