### ISSUE TITLE
How to programmatically set the selected value?

### ISSUE THREAD

**Issue by euwyn** [chymtt/ReactNativeDropdownAndroid#8]
The 'selected' prop works well to set the initially selected value, but given that we can't change props, is there a way to programmatically change the value?

**Comment by chymtt** [comment]
You can always use state. For example:

```
<Dropdown
    style={...}
    values={...}
    selected={this.state.selected} />
```

And somewhere else:

```
this.setState({ selected: 2 });
```

Hope that helps!
